### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by felipemoslavacz** [divriots/story-to-design#153] opened 2024-03-08 14:13 UTC
## Describe the problem ##

The canvas is completely empty, it should have a title, description and CTA (despite the broken images).

---
Bug report identity: Please do not edit

Task path: iy5LAnxjYjDyTYLu2Haf/nqkzW9yDN8IslZC7Hz6M/18ho3dh1hs932u

**Comment by muryoh** [comment] 2024-03-12 11:07
Hi @felipemoslavacz,

Interesting - this is what I'm getting: 
![image](https://github.com/divriots/story-to-design/assets/1789748/154d2fbf-bc8c-4b7d-897b-d0182f7e8988)


Yours is completely empty?

**Comment by felipemoslavacz** [comment] 2024-03-12 15:09
@muryoh Thanks for testing, I checked again after clicking Reprocess story and the problem seems to be gone, maybe it was a glitch the first time I used it.

**Comment by muryoh** [comment] 2024-03-12 15:23
I do see some unexpected behavior regarding `viewport`, investigating :pray:

**Comment by muryoh** [comment] 2024-03-12 18:20
Hi there, could not reproduce after all - the viewport thing I mentioned was unrelated

I'll be closing for now, but do not hesitate to reopen if needed!

Cheers
Remy

**Closed as completed by muryoh** 2024-03-12 18:20 UTC
