### ISSUE TITLE
Unwanted component resizing

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#110] opened 2023-09-13 12:19 UTC
## Describe the problem ##
The Accordion component is resized via the plugin even though this does not match our Storybook:
<img width="1356" alt="Screenshot 2023-09-13 at 13 36 28" src="https://github.com/divriots/story-to-design/assets/129752452/56007c2d-e045-43fb-8001-9f4edadb2581">
<img width="373" alt="Screenshot 2023-09-13 at 14 19 05" src="https://github.com/divriots/story-to-design/assets/129752452/1b0e65ab-1dec-4bc3-bec3-f9666b5a13ee">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/4yliGsRsjDiI50BV9Add/14owycc1q2ir7h

**Comment by gqio** [comment] 2023-09-25 12:37
Duplicate of #109 

Please look at my comment on the #109 for this unwanted behaviour.

Best.

**Closed as completed by gqio** 2023-09-25 12:37 UTC
