### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by angelceballos** [divriots/story-to-design#136] opened 2024-02-07 14:35 UTC
Caret isn't aligned on nested multi drop-down

![CleanShot 2024-02-07 at 09 35 20@2x](https://github.com/divriots/story-to-design/assets/494326/51d1e227-bd26-4d82-9b58-43fdf5c336a5)

---
Bug report identity: Please do not edit

Task path: kfVuAGTppOF6aACDd7PR/RA48GoZeLurkIDBT8BNx/fl8uub1k6yn9g

**Comment by katrynmc** [comment] 2024-02-15 18:57
I suspect my issue may be a dupe of this https://github.com/divriots/story-to-design/issues/145

**Comment by muryoh** [comment] 2024-02-16 10:25
Hi there, thanks for letting us know, having a look!

**Comment by muryoh** [comment] 2024-02-16 10:40
~~From my testing this seems to happen after an update or a reset, not on the initial add to canvas
Can you confirm this is your situation?~~

~~If it is, we have a fix that should be ready soon~~

Apologies, does seem to happen on initial add to canvas in your case, looking into it

**Closed as completed** 2024-02-16 17:16 UTC

**Comment by muryoh** [comment] 2024-02-16 17:43
We just released a new version of the agent which should avoid the caret not being aligned

I did notice that autolayout was not working in that case though - so if it is something that you'd like do not hesitate to reopen the issue!

Best regards,
Remy
