### ISSUE TITLE
Import discrepancy between local instance and live Storybook site

### ISSUE THREAD

**Issue by chungsi** [divriots/story-to-design#92] opened 2023-08-08 21:42 UTC
## Describe the problem ##

When I'm importing this component from the live Storybook site, the first card of the grid will have the wrong formatting/size.
![image](https://github.com/divriots/story-to-design/assets/14225300/0a9c2b6f-809f-4b86-a60a-5fea2c48e5b2)

However, when I switch to dev mode on the same branch that's deployed (so it's the same code that's live), the imported sizes are fine.
![image](https://github.com/divriots/story-to-design/assets/14225300/5790403d-a80b-4755-befe-a8464c33283a)

Let me know if you'd like a ticket for the other version to compare as well! I'm super confused why this is happening...

---
Bug report identity: Please do not edit

Task path: R702fkgNoAQvwSdKueSF/tOibszywZThBMr4v1chn/1rkr1fbgfjxz1

**Comment by muryoh** [comment] 2023-08-09 10:28
Hi there, I can't seem to be able to reproduce 🤔 

Is a specific variant faulty?
![image](https://github.com/divriots/story-to-design/assets/1789748/a47ae66e-3a7a-4737-b092-d5d401f96c21)

Could you maybe try to `Reprocess` then `Reset canvas` (or update if there were changes)?
![image](https://github.com/divriots/story-to-design/assets/1789748/84fa9820-2d63-45b6-875a-92ddaa4c9cb4)

**Comment by chungsi** [comment] 2023-08-09 17:15
Very strange... I Reprocessed and Reset Canvas and now the cards fill the right space but the image/text of the first card is only filling a part of the card. This issue is on all the variants.

However, the component only imports wonky when I connect to the live Storybook site (https://alterramtn.design/ -> Organisms/ActivitiesResults). When I import from a local instance of Storybook through dev mode, everything is correct.

![image](https://github.com/divriots/story-to-design/assets/14225300/4acf79dd-ca56-4c46-a6fe-60f4b50acbcd)

**Comment by muryoh** [comment] 2023-08-17 09:29
Hi @chungsi , would you mind trying again with the new version? Since I was not able to reproduce I would like to see if maybe it was fixed by the many fixes delivered in the last version :pray:

**Comment by chungsi** [comment] 2023-08-28 20:12
@muryoh Sorry it's still not working 😔 
![image](https://github.com/divriots/story-to-design/assets/14225300/cec5682d-802d-43d0-a3a7-aa6d58fe6e5b)

I'm ok with you closing this ticket since you can't reproduce. It may be related to missing fonts as well (one of my other tickets: https://github.com/divriots/story-to-design/issues/91)?

**Comment by gqio** [comment] 2023-08-30 11:34
Hello @chungsi 

We released a new version with a lot of fixes with autolayout, could you please confirm this new version is fixing your Issue ?

Best

PS: feel free to reopen if it's not the case with the latest version on your side (both plugin and agent needs to be updated)

**Closed as completed by gqio** 2023-08-30 11:34 UTC

**Comment by chungsi** [comment] 2023-08-30 16:35
@gqio @muryoh OOH IT'S WORKING NOW! WOOHOO!! Thanks so much for all the help!!!
